# Generated by Django 5.0.3 on 2026-05-06 07:28

import internships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('college_name', models.CharField(max_length=255, verbose_name='College/University')),
                ('skills', models.TextField(verbose_name='Skills')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Experience')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('resume', models.FileField(upload_to=internships.models.rename_resume, verbose_name='Resume File')),
                ('message', models.TextField(verbose_name='Why do you want to join?')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
